### ISSUE TITLE
Homepage set as "Last opened Object" does not go to the "Last opened Object" upon updating to 0.41.0

### ISSUE THREAD

**Issue by herobrine369** [anyproto/anytype-ts#771] opened 2024-06-12 02:36 UTC
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

I set "Homepage" as "Last opened Object". When I login every time, the page goes to the one which asks the user to set the "Homepage".

### Expected Behavior

After every login, the application should go to the previously accessed object.

### Steps To Reproduce

1. The settings are configured as below: 
    > Space...
    > Homepage: Last opened Object
    > Default Object Type: Note
2. Restart the app.

### Environment

```markdown
- OS: macOS Sonoma 14.3.1 (Apple Silicon)
- Version: 0.41.0
```

### Anything else?

The screenshot of the page after login:
<img width="1007" alt="Screenshot 2024-06-12 at 10 18 03" src="https://github.com/anyproto/anytype-ts/assets/63570128/9aad7ef1-6d29-4535-bee1-649a0d2aee91">

**Comment by ra3orblade** [comment] 2024-06-12 07:34
I can't reproduce this behaviour at the moment, though sometimes it opens empty object for me. I've tried to logout/login and reopen the app and it opens on the last object.

**Comment by ra3orblade** [comment] 2024-06-12 07:52
Found the problem, fixed.

**Comment by herobrine369** [comment] 2024-06-14 16:10
Updating to 0.41.1, it seems that the problem hasn't been fixed yet. I even reinstalled the application, but it could help nothing. It's now still all same as before.

**Comment by ra3orblade** [comment] 2024-07-03 17:46
> Updating to 0.41.1, it seems that the problem hasn't been fixed yet. I even reinstalled the application, but it could help nothing. It's now still all same as before.

It's fixed in the current main branch, not 0.41.1. You can check latest alpha version.

**Comment by herobrine369** [comment] 2024-07-10 06:57
FYR, one of the lines in the log says "QueryByIds failed to find id: lastOpened". I'm not sure if it's relevant to the issue.

**Comment by ra3orblade** [comment] 2024-07-10 08:22
> FYR, one of the lines in the log says "QueryByIds failed to find id: lastOpened". I'm not sure if it's relevant to the issue.

Found another problem with this logic that correct space was not switching when you log in, can't reproduce the problem with last opened object apart from this bug.

**Comment by ra3orblade** [comment] 2024-08-20 08:25
Closing, no response.

**Closed by ra3orblade** 2024-08-20 08:25 UTC
Labels: bug
