### ISSUE TITLE
FYI Microsoft Defender warning

### ISSUE THREAD

**Issue by hightowertech** [anyproto/anytype-ts#84] opened 2023-07-20 15:10 UTC
**Describe the bug**
Windows defender gave me a nasty screen warning me that your windows installer may damage my system or put me at risk

**To Reproduce**
Have windows defender up to date and running, download and start the windows installer

**Expected behavior**
Install program no problems

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: latest windows installer downloadable now

**Comment by ra3orblade** [comment] 2023-07-21 16:01
Share some screenshots pls

**Comment by rluks** [comment] 2023-07-23 01:31
I'm getting unknown publisher warning "windows protected your pc" when executing Anytype.Setup.0.33.3 on Win 10.

Apparently, Anytype needs to gain reputation? Related links:

* https://github.com/postmanlabs/postman-app-support/issues/7214
* https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

I've submitted the file for analysis as suggested by https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/ and checked "Incorrectly detected as malware/malicious".

**Comment by hightowertech** [comment] 2023-07-23 10:00
> Share some screenshots pls

https://i.imgur.com/3Ri0eUQ.png
tried it on 2 diff computers both running windows 10 so it wasnt a 1 off fluke.

**Comment by ra3orblade** [comment] 2023-07-23 16:30
> I'm getting unknown publisher warning "windows protected your pc" when executing Anytype.Setup.0.33.3 on Win 10.
> 
> Apparently, Anytype needs to gain reputation? Related links:
> 
> * ["Windows protected your PC" warning while installing Postman for Windows postmanlabs/postman-app-support#7214](https://github.com/postmanlabs/postman-app-support/issues/7214)
> * https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro
> 
> I've submitted the file for analysis as suggested by https://learn.microsoft.com/en-us/windows/security/operating-system-security/virus-and-threat-protection/microsoft-defender-smartscreen/ and checked "Incorrectly detected as malware/malicious".

Yes, we have a certificate that needs to gain reputation, we plan to change to EV certificate to remove reputation requirements.

**Comment by ra3orblade** [comment] 2023-07-24 11:48
Closing for now

**Closed by ra3orblade** 2023-07-24 11:48 UTC
Labels: bug

**Comment by mekefly** [comment] 2024-10-26 09:52
The antivirus engine indicates the presence of a virus.

Both Huorong 6 and Palo Alto Networks have detected a Trojan virus. Previous versions reported a downloader virus. I hope this issue can be resolved or the cause can be identified. Thank you.


Eg
![image](https://github.com/user-attachments/assets/5c1cd3ca-02b3-4ef1-a4b6-2869b009b5ab)
https://www.virustotal.com/gui/file/adf74f6d598fe9d23cf0dcb96f3e9975caeb3c1bcd5f784d3319513dbfa24ed2
![image](https://github.com/user-attachments/assets/c0c7111f-07a3-48b4-b125-df4339838d69)
