### ISSUE TITLE
Anytype for Windows built from source fails to open: util.js not found

### ISSUE THREAD

**Issue by SamBouwer** [anyproto/anytype-ts#159] opened 2023-08-05 20:08 UTC
### Have you read a contributing guide?

- [X] I have read CONTRIBUTING.md
- [X] I have searched the existing issues and didn't find any that were similar
- [X] I have considered creating a pull request with fixes instead of a bug report and want to proceed

### Current Behavior

Building as described in my script: https://github.com/SamBouwer/any-docker/blob/main/scripts/build_heart_client_win.sh

Result:

![image](https://github.com/anyproto/anytype-ts/assets/6918900/cbef4b17-a920-406e-9a2b-c86f757b62c6)

It looks like this file is not written to the built installer (also not to win-unpacked folder) because the `SENTRY_AUTH_TOKEN` is missing (not provided in tech-docs or elsewhere AFAIK).

Relevant part of the build log:

```
WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

webpack 5.88.2 compiled with 3 warnings in 43103 ms
  • electron-builder  version=24.6.3 os=5.15.0-78-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
[BeforeBuild] platform: windows arch: x64
[BeforeBuild] folder:
  • packaging       platform=win32 arch=x64 electron=22.0.0 appOutDir=dist/win-unpacked
error: API request failed
  caused by: sentry reported an error: Authentication credentials were not provided. (http status: 401)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
  • building        target=nsis file=dist/Anytype Setup 0.33.6-alpha.exe archs=x64 oneClick=true perMachine=false
  • building block map  blockMapFile=dist/Anytype Setup 0.33.6-alpha.exe.blockmap
```

### Expected Behavior

Either the build process to fail gracefully and notify the user the SENTRY_AUTH_TOKEN is required, or allow the build to complete properly without this token (and Sentry hooks disabled)

### Steps To Reproduce

1. Build Anytype for Windows as per instructions in Anytype tech-docs
2. Take the installer that is the result of the build process
3. Install the file on a Windows machine
4. See the error as shared above

### Environment

```markdown
- OS: Windows
- Version: 
Edition	Windows 11 Home Insider Preview
Version	23H2
Installed on	‎7/‎31/‎2023
OS build	25915.1000
Experience	Windows Feature Experience Pack 1000.25915.1000.0
```

**Comment by ra3orblade** [comment] 2023-08-05 20:15
Yeah, I've added sentry hook for the CI today, will fix tomorrow with env skip var. Btw I've added skip env var for the sign hook so running `ELECTRON_SKIP_NOTARIZE=1 npm run dist:win` will skip the signing hook.

**Comment by ra3orblade** [comment] 2023-08-05 20:16
To fix language problem run `npm run update:locale`, I have not added this to npm dist command since it may invoke github rate limits as language files are downloaded via github API, gotta change the docs I suppose.

**Comment by SamBouwer** [comment] 2023-08-05 20:20
Testing :) (takes a minute or 15)

**Comment by ra3orblade** [comment] 2023-08-05 22:20
How do you build it?

**Comment by ra3orblade** [comment] 2023-08-05 22:26
I've added ELECTRON_SKIP_SENTRY flag that skips sentry upload

**Comment by Shampra** [comment] 2023-08-07 16:41
It seems to work, thank you @ra3orblade .
(and Thank you @SamBouwer , every error I've encountered has already been reported, I should have started with your script 😅)

I can launch with dev-win, it's work.
If I do start:dev, no error. I can install with "Anytype Setup 0.33.6-alpha" file. But When I launch the app installed (ou with win-unpacked) I've this error : 
![image](https://github.com/anyproto/anytype-ts/assets/16141040/ce4d1e5e-d72e-4d63-a513-494defc24c73)
(possibly a mistake on my part, see if @SamBouwer  has the same result)

**Comment by SamBouwer** [comment] 2023-08-07 16:48
Try again with my current main branch, building the windows installer should work!

**Comment by ra3orblade** [comment] 2023-08-08 09:51
This is the problem with package deps that are not building on CI for windows, try `npm run build:deps`

**Comment by Shampra** [comment] 2023-08-19 16:19
I've tried both, same error 😢. If you've succeeded, there's something wrong with my environment (or my actions).
I'm not giving up, but if you have any other ideas for a viable executable, I'd love to hear from you.

I was hoping to develop, but if I can't even get past the compilation stage, I'm in trouble.

**Comment by ra3orblade** [comment] 2023-08-28 18:53
Does it still reproduce?

**Comment by SamBouwer** [comment] 2023-08-28 21:39
It is resolved for me. @Shampra how about you?

**Comment by Shampra** [comment] 2023-08-31 09:42
Unfortunately, no. But I might be an isolated case: without further confirmation of the issue, I'm not sure if it's relevant to keep it open (and for me, I can do without it for now).

The same issue persists even **with the procedure here** _(git bash on Windows 11)_. 
Here are the commands used (without any error):

```
git clone https://github.com/anyproto/anytype-ts
cd anytype-ts
npm install -D

./update.sh windows-latest

jq 'del(.build.win.sign)' package.json >> package_new.json
rm package.json
mv package_new.json package.json

npm exec electron-builder@24.6.3 install-app-deps --platform=win32 --arch=x64
npm run update:locale
ELECTRON_SKIP_NOTARIZE=1 ELECTRON_SKIP_SENTRY=1 npm run dist:win
```

Command `SERVER_PORT=1443 ANYPROF=:1444 npm run start:dev-win` works well...



**Regarding the installation of @SamBouwer** (_WSL Ubuntu on Windows 11_) , I encountered errors (and I confess I didn't take the time to report or analyze them, as I don't actually need that for now).

**Comment by sirito97** [comment] 2023-09-22 15:28
> It seems to work, thank you @ra3orblade . (and Thank you @SamBouwer , every error I've encountered has already been reported, I should have started with your script 😅)
> 
> I can launch with dev-win, it's work. If I do start:dev, no error. I can install with "Anytype Setup 0.33.6-alpha" file. But When I launch the app installed (ou with win-unpacked) I've this error : ![image](https://user-images.githubusercontent.com/16141040/258872099-ce4d1e5e-d72e-4d63-a513-494defc24c73.png) (possibly a mistake on my part, see if @SamBouwer has the same result)

I have the same error on win11, have you been able to solve it?

**Comment by ra3orblade** [comment] 2024-01-17 14:42
Does it still reproduce?

**Comment by ra3orblade** [comment] 2024-04-28 17:18
Closing since there are no replies.

**Closed by ra3orblade** 2024-04-28 17:18 UTC
Labels: bug
